apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  type: NodePort
  selector:
    app: front-deployment
  ports:
  - port: 80
    targetPort: http-front
    nodePort: 30100
    protocol: TCP